<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerROJQyBn\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerROJQyBn/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerROJQyBn.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerROJQyBn\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerROJQyBn\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ROJQyBn',
    'container.build_id' => 'd6867a97',
    'container.build_time' => 1646602733,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerROJQyBn');
