<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5CZyfEj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5CZyfEj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5CZyfEj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5CZyfEj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container5CZyfEj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '5CZyfEj',
    'container.build_id' => 'd63844d4',
    'container.build_time' => 1646665322,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5CZyfEj');
